create extension if not exists pgcrypto;

create table if not exists public.game_levels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  prize text not null,
  rank integer not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint game_levels_rank_positive check (rank > 0)
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  value text not null,
  level_id bigint not null references public.game_levels (id) on delete cascade,
  points integer not null default 0,
  true_answer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint questions_points_non_negative check (points >= 0)
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions (id) on delete cascade,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint answers_question_value_unique unique (question_id, value)
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users (id) on delete cascade,
  total_points integer not null default 0,
  achieved_level bigint references public.game_levels (id) on delete set null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  current_question_id bigint references public.questions (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_total_points_non_negative check (total_points >= 0),
  constraint games_finished_after_start check (
    finished_at is null or finished_at >= started_at
  )
);

create table if not exists public.user_answers (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games (id) on delete cascade,
  question_id bigint not null references public.questions (id) on delete cascade,
  answer_id bigint not null references public.answers (id) on delete cascade,
  level bigint references public.game_levels (id) on delete set null,
  points integer not null default 0,
  is_true boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_answers_points_non_negative check (points >= 0),
  constraint user_answers_unique_submission unique (game_id, question_id)
);

create index if not exists questions_level_id_idx on public.questions (level_id);
create index if not exists answers_question_id_idx on public.answers (question_id);
create index if not exists games_owner_idx on public.games (owner);
create index if not exists games_current_question_id_idx on public.games (current_question_id);
create index if not exists games_achieved_level_idx on public.games (achieved_level);
create index if not exists user_answers_game_id_idx on public.user_answers (game_id);
create index if not exists user_answers_question_id_idx on public.user_answers (question_id);
create index if not exists user_answers_answer_id_idx on public.user_answers (answer_id);
create index if not exists user_answers_level_idx on public.user_answers (level);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_game_levels_updated_at on public.game_levels;
create trigger set_game_levels_updated_at
before update on public.game_levels
for each row execute function public.set_updated_at();

drop trigger if exists set_questions_updated_at on public.questions;
create trigger set_questions_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

drop trigger if exists set_answers_updated_at on public.answers;
create trigger set_answers_updated_at
before update on public.answers
for each row execute function public.set_updated_at();

drop trigger if exists set_games_updated_at on public.games;
create trigger set_games_updated_at
before update on public.games
for each row execute function public.set_updated_at();

drop trigger if exists set_user_answers_updated_at on public.user_answers;
create trigger set_user_answers_updated_at
before update on public.user_answers
for each row execute function public.set_updated_at();

alter table public.game_levels enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.games enable row level security;
alter table public.user_answers enable row level security;

drop policy if exists "Authenticated users can read game levels" on public.game_levels;
create policy "Authenticated users can read game levels"
on public.game_levels
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read questions" on public.questions;
create policy "Authenticated users can read questions"
on public.questions
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read answers" on public.answers;
create policy "Authenticated users can read answers"
on public.answers
for select
to authenticated
using (true);

drop policy if exists "Users can read their games" on public.games;
create policy "Users can read their games"
on public.games
for select
to authenticated
using (owner = auth.uid());

drop policy if exists "Users can create their games" on public.games;
create policy "Users can create their games"
on public.games
for insert
to authenticated
with check (owner = auth.uid());

drop policy if exists "Users can update their games" on public.games;
create policy "Users can update their games"
on public.games
for update
to authenticated
using (owner = auth.uid())
with check (owner = auth.uid());

drop policy if exists "Users can delete their games" on public.games;
create policy "Users can delete their games"
on public.games
for delete
to authenticated
using (owner = auth.uid());

drop policy if exists "Users can read their answers" on public.user_answers;
create policy "Users can read their answers"
on public.user_answers
for select
to authenticated
using (
  exists (
    select 1
    from public.games games_owner
    where games_owner.id = game_id
      and games_owner.owner = auth.uid()
  )
);

drop policy if exists "Users can create their answers" on public.user_answers;
create policy "Users can create their answers"
on public.user_answers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.games games_owner
    where games_owner.id = game_id
      and games_owner.owner = auth.uid()
  )
);

drop policy if exists "Users can update their answers" on public.user_answers;
create policy "Users can update their answers"
on public.user_answers
for update
to authenticated
using (
  exists (
    select 1
    from public.games games_owner
    where games_owner.id = game_id
      and games_owner.owner = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.games games_owner
    where games_owner.id = game_id
      and games_owner.owner = auth.uid()
  )
);

drop policy if exists "Users can delete their answers" on public.user_answers;
create policy "Users can delete their answers"
on public.user_answers
for delete
to authenticated
using (
  exists (
    select 1
    from public.games games_owner
    where games_owner.id = game_id
      and games_owner.owner = auth.uid()
  )
);
